project:
  render:
    - "*.qmd"
    - "!/Templates"
    - "!/Data"
    - "!/Images"
    - "!/Projects/Archive"
    - "!/Setup/Archive"
    - "!/Workbooks/Archive"
  type: website

website:
  title: "DS 250!"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  issue-url: https://github.com/byuistats/DS250-Course/issues/new
  repo-url: https://github.com/byuistats/DS250-Course
  repo-actions: [issue]
  
  # [layout](https://quarto.org/docs/output-formats/page-layout.html)

  page-footer: 
    border: true
    left: "J. Hathaway, Chaz Clark, David Palmer BYU-I 2025Â©"
    right: 
      - icon: github
        href: https://github.com/byuidatascience
      - icon: linkedin
        href: https://www.linkedin.com/groups/13537407/

  navbar:
    background: primary
    search: true   
    right:
      # - text: "Home"
      #   file: index.qmd
      - text: "Setup"
        file: setup.qmd
      - text: "Unit 0 Set-up Check"
        file: Projects/project_0_dp.qmd
      - text: "Unit 1 Graphing"
        menu:
          - text: "Task 1"
            file: Projects/unit1_task1.qmd
          - text: "Task 2"
            file: Projects/unit1_task2.qmd
          - text: "Task 3"
            file: Projects/unit1_task3.qmd
          - text: "Task 4"
            file: Projects/unit1_task4.qmd
      - text: "Unit 2 SQLite"
        menu:
          - text: "Task 1"
            file: Projects/unit2_task1.qmd
          - text: "Task 2"
            file: Projects/unit2_task2.qmd
          - text: "Task 3"
            file: Projects/unit2_task3.qmd
          - text: "Task 4"
            file: Projects/unit2_task4.qmd
      - text: "Unit 3 Wrangling"
        menu:
          - text: "Task 1"
            file: Projects/unit3_task1.qmd
          - text: "Task 2"
            file: Projects/unit3_task2.qmd
          - text: "Task 3"
            file: Projects/unit3_task3.qmd
          - text: "Task 4"
            file: Projects/unit3_task4.qmd
      - text: "Unit 4 ML"
        menu:
          - text: "Task 1"
            file: Projects/unit4_task1.qmd
          - text: "Task 2"
            file: Projects/unit4_task2.qmd
          - text: "Task 3"
            file: Projects/unit4_task3.qmd
          - text: "Task 4"
            file: Projects/unit4_task4.qmd
      - text: "Unit 5 ML Prep"
        menu:
          - text: "Task 1"
            file: Projects/unit5_task1.qmd
          - text: "Task 2"
            file: Projects/unit5_task2.qmd
          - text: "Task 3"
            file: Projects/unit5_task3.qmd
          - text: "Task 4"
            file: Projects/unit5_task4.qmd
      - text: "GitHub Task"
        file: Projects/unit6.qmd
      # - text: "Workbooks"
      #   file: workbooks.qmd
      # - text: "Book Time with Us"
      #   file: contact.qmd
      # - text: "Syllabus"
      #   file: Syllabus/syllabus.qmd
      # - text: "Skill Builders"
      #   file: skill_builders.qmd
      - text: "FAQ"
        file: faq.qmd
      
  sidebar:
    - title: "Projects"
      style: "docked"
      background: light
      contents:
        - text: "Projects"
          file: projects.qmd
        - text: "---"
        - text: "Project 0: Introduction"
          file: Projects/project_0.qmd
        - text: "---"
        - text: "Project 1: What's in a Name?"
          file: Projects/project_1.qmd
        - text: "---"
        - text: "Project 2: Finding Relationships in Baseball"
          file: Projects/project_2.qmd
        - text: "---"
        - text: "Project 3: Late Flights and Missing Data (JSON)"
          file: Projects/project_3.qmd
        - text: "---"
        - text: "Project 4: Can You Predict That?"
          file: Projects/project_4.qmd
        - text: "---"
        - text: "Project 5: The War with Star Wars"
          file: Projects/project_5.qmd
        - text: "---"
        - text: "Project 6: Git Your Portfolio Online"
          file: Projects/project_6.qmd
        - text: "---"

    # - title: "Book Time"
    #   contents:
    #     - text: "Book Time with Us"
    #       file: contact.qmd
    #     # navigation items

    - title: "Setup"
      contents:
        - text: "Setup"
          file: setup.qmd
        - text: "---"
        - text: "AWS VM (Optional)"
          file: Setup/aws_setup.qmd
        - text: "---"
        - text: "Slack"
          file: Setup/slack_setup.qmd
        - text: "---"
        - text: "Python"
          file: Setup/python_setup.qmd
        - text: "---"
        - text: "Python Libraries"
          file: Setup/python_lib.qmd
        - text: "---"
        - text: "VS Code"
          file: Setup/vs_code_setup.qmd
        - text: "---"
        - text: "Quarto"
          file: Setup/quarto_setup.qmd
        - text: "---"
        - text: "Git and Github"
          file: Setup/git_github_setup.qmd
        - text: "---"
        - text: "SQL"
          file: Setup/sql_setup.qmd
        - text: "---"
        - text: "Copilot"
          file: Setup/copilot_setup.qmd
        - text: "---"

    - title: "Materials"
      contents:
        - text: "Course Materials"
          file: materials.qmd
        - text: "---"
        - text: "VS Code"
          file: Course Materials/vs_code.qmd
        - text: "---"
        - text: "Lets Plot"
          file: Course Materials/lets_plot.qmd
        - text: "---"
        # - text: "Altair"
        #   file: Course Materials/altair.qmd
        # - text: "---"
        # - text: "Plotly Express"
        #   file: Course Materials/plotly_express.qmd
        # - text: "---"
        - text: "Python for Data Science"
          file: Course Materials/python.qmd
        - text: "---"
        - text: "SQLite"
          file: Course Materials/sql.qmd
        - text: "---"
        - text: "Machine Learning (ML)"
          file: Course Materials/ml.qmd
        - text: "---"
        - text: "GitHub - Pull and Merge Forks"
          file: Course Materials/git_pull_merge.qmd
        - text: "---"

    - title: "Syllabus"
      contents:
        - text: "Syllabus"
          file: Syllabus/syllabus.qmd
        - text: "---"
        - text: "Competency"
          file: Syllabus/competency.qmd
        - text: "---"

    - title: "Workbooks"
      contents:
        - text: "Course Workbooks"
          file: workbooks.qmd
        - text: "---"
        - text: "Project 0"
          file: Workbooks/wb0.qmd
        - text: "---"
        - text: "Project 1"
          file: Workbooks/wb1.qmd
        - text: "---"
        - text: "Project 2"
          file: Workbooks/wb2.qmd
        - text: "---"
        - text: "Project 3"
          file: Workbooks/wb3.qmd
        - text: "---"
        - text: "Project 4"
          file: Workbooks/wb4.qmd
        - text: "---"
        - text: "Project 5"
          file: Workbooks/wb5.qmd
        - text: "---"
        - text: "Project 6"
          file: Workbooks/wb6.qmd
        - text: "---"
        
    - title: "Skill Builders"
      contents:
        - text: "Skill Builders"
          file: skill_builders.qmd
        - text: "---"
        - text: "Project 0: Introduction"
          file: Skill Builders/introduction.qmd
        - text: "---"
        - text: "Project 1: Pandas and LetsPlot"
          file: Skill Builders/pandas_letsplot.qmd
        - text: "---"
        - text: "Project 2: JSON & Missing"
          file: Skill Builders/json_missing.qmd
        - text: "---"
        - text: "Project 3: SQL & Databases"
          file: Skill Builders/relational_data.qmd
        - text: "---"
        - text: "Project 4: Machine Learning"
          file: Skill Builders/ml_sklearn.qmd
        - text: "---"
        - text: "Project 5: Munging Data"
          file: Skill Builders/munging.qmd
        - text: "---"
        - text: "Project 6: GitHub and Git"
          file: Skill Builders/git_github.qmd
        - text: "---"

    # - title: "FAQ"
    #   contents:
    #     - faq.qmd
    #     # navigation items

format:  
  html:
    theme:
      light: flatly
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



